### ISSUE TITLE
Is my gpx format wrong?

### ISSUE THREAD

**Issue by goamberg** [remisalmon/gpx_interpolate#4]
Hi

This is a great script! But I am having small troubles here on my end with gpx conversions.
Some I am able to get to work and some do not.
This is a gpsbabel conversion from a kml track and somehow I get errors. (no timestamps)

I hope you can push me a little in the right direction? 

edit:
removed file

Thanks in advance
Goam

**Comment by remisalmon** [comment]
The last point of your gpx file does not have a `<time>` tag which throws the error.

The code should check for missing tags before adding a point to the data, thanks for reporting!

**Comment by goamberg** [comment]
Thanks! This I totally overlooked. Its the base reference point.
