### ISSUE TITLE
Calculated speed option?

### ISSUE THREAD

**Issue by goamberg** [remisalmon/gpx_interpolate#7]
Is it maybe possible for you to add a calculated speed option? (- s speed)
With having the distance (-res) it would be "only" a division to the time difference of 2 timestamps (m/s)

My problem is, that every conversion and speed calculator of your high precision gpx files cancel out the digits after milliseconds.
With calculation at your precise level in this script and conversion after the fact to my programs, it would somewhat eliminate this problem.

**Comment by remisalmon** [comment]
That's a valid issue, I will add the option to save the speed.

The output file will have to use the 1.0 Schema, for ref: https://github.com/tkrajina/gpxpy#gpx-version

**Comment by goamberg** [comment]
Hi...Its me again on that topic ;-).
We used the script in our studies a lot in the last months!

With some data I get steps in the speed data. Propably cause of the "only" 9 digits in LAT/LON.
Is there a way to crank it up a little for the speed calcs internally?
![image](https://user-images.githubusercontent.com/26245753/98471575-9246a080-21ed-11eb-99bf-a9d0211f0486.png)

I absolutely know more than 9 digits makes no sense for coordinates (8 is already mm) and that our high frequency interpolation  is also not very "real life"...but for us its more the scientific side of things :-D

But I would understand if you let it stay as is....
goamberg

**Comment by remisalmon** [comment]
Please open a new issue and upload a sample GPX file.
